<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="../assets/style.css">
</head>
<body>
    <?php require_once __DIR__ . '\..\components\navbar.php'; ?>
    
    <?php require_once __DIR__ . '\..\components\sidebar.php'; ?>

    <main>
        <h1>Conteúdo</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus assumenda unde aspernatur eligendi architecto, aperiam sunt laborum, vel rem quo obcaecati. Itaque doloribus natus necessitatibus, ex alias ut ipsa ea! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur qui animi tempora iure voluptatibus sapiente laudantium esse, aliquid maiores dolorum molestiae aperiam iste nulla sit aut quasi ipsa officia. Iure. Lorem ipsum dolor sit amet consectetur adipisicing elit. A aliquam dolorem omnis repellendus fugit placeat fuga libero, quos consequatur, tempora autem animi odit sapiente neque nulla officia doloribus praesentium. Quasi.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus assumenda unde aspernatur eligendi architecto, aperiam sunt laborum, vel rem quo obcaecati. Itaque doloribus natus necessitatibus, ex alias ut ipsa ea! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur qui animi tempora iure voluptatibus sapiente laudantium esse, aliquid maiores dolorum molestiae aperiam iste nulla sit aut quasi ipsa officia. Iure. Lorem ipsum dolor sit amet consectetur adipisicing elit. A aliquam dolorem omnis repellendus fugit placeat fuga libero, quos consequatur, tempora autem animi odit sapiente neque nulla officia doloribus praesentium. Quasi.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus assumenda unde aspernatur eligendi architecto, aperiam sunt laborum, vel rem quo obcaecati. Itaque doloribus natus necessitatibus, ex alias ut ipsa ea! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur qui animi tempora iure voluptatibus sapiente laudantium esse, aliquid maiores dolorum molestiae aperiam iste nulla sit aut quasi ipsa officia. Iure. Lorem ipsum dolor sit amet consectetur adipisicing elit. A aliquam dolorem omnis repellendus fugit placeat fuga libero, quos consequatur, tempora autem animi odit sapiente neque nulla officia doloribus praesentium. Quasi.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus assumenda unde aspernatur eligendi architecto, aperiam sunt laborum, vel rem quo obcaecati. Itaque doloribus natus necessitatibus, ex alias ut ipsa ea! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur qui animi tempora iure voluptatibus sapiente laudantium esse, aliquid maiores dolorum molestiae aperiam iste nulla sit aut quasi ipsa officia. Iure. Lorem ipsum dolor sit amet consectetur adipisicing elit. A aliquam dolorem omnis repellendus fugit placeat fuga libero, quos consequatur, tempora autem animi odit sapiente neque nulla officia doloribus praesentium. Quasi.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus assumenda unde aspernatur eligendi architecto, aperiam sunt laborum, vel rem quo obcaecati. Itaque doloribus natus necessitatibus, ex alias ut ipsa ea! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur qui animi tempora iure voluptatibus sapiente laudantium esse, aliquid maiores dolorum molestiae aperiam iste nulla sit aut quasi ipsa officia. Iure. Lorem ipsum dolor sit amet consectetur adipisicing elit. A aliquam dolorem omnis repellendus fugit placeat fuga libero, quos consequatur, tempora autem animi odit sapiente neque nulla officia doloribus praesentium. Quasi.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus assumenda unde aspernatur eligendi architecto, aperiam sunt laborum, vel rem quo obcaecati. Itaque doloribus natus necessitatibus, ex alias ut ipsa ea! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur qui animi tempora iure voluptatibus sapiente laudantium esse, aliquid maiores dolorum molestiae aperiam iste nulla sit aut quasi ipsa officia. Iure. Lorem ipsum dolor sit amet consectetur adipisicing elit. A aliquam dolorem omnis repellendus fugit placeat fuga libero, quos consequatur, tempora autem animi odit sapiente neque nulla officia doloribus praesentium. Quasi.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus assumenda unde aspernatur eligendi architecto, aperiam sunt laborum, vel rem quo obcaecati. Itaque doloribus natus necessitatibus, ex alias ut ipsa ea! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur qui animi tempora iure voluptatibus sapiente laudantium esse, aliquid maiores dolorum molestiae aperiam iste nulla sit aut quasi ipsa officia. Iure. Lorem ipsum dolor sit amet consectetur adipisicing elit. A aliquam dolorem omnis repellendus fugit placeat fuga libero, quos consequatur, tempora autem animi odit sapiente neque nulla officia doloribus praesentium. Quasi.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus assumenda unde aspernatur eligendi architecto, aperiam sunt laborum, vel rem quo obcaecati. Itaque doloribus natus necessitatibus, ex alias ut ipsa ea! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur qui animi tempora iure voluptatibus sapiente laudantium esse, aliquid maiores dolorum molestiae aperiam iste nulla sit aut quasi ipsa officia. Iure. Lorem ipsum dolor sit amet consectetur adipisicing elit. A aliquam dolorem omnis repellendus fugit placeat fuga libero, quos consequatur, tempora autem animi odit sapiente neque nulla officia doloribus praesentium. Quasi.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus assumenda unde aspernatur eligendi architecto, aperiam sunt laborum, vel rem quo obcaecati. Itaque doloribus natus necessitatibus, ex alias ut ipsa ea! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur qui animi tempora iure voluptatibus sapiente laudantium esse, aliquid maiores dolorum molestiae aperiam iste nulla sit aut quasi ipsa officia. Iure. Lorem ipsum dolor sit amet consectetur adipisicing elit. A aliquam dolorem omnis repellendus fugit placeat fuga libero, quos consequatur, tempora autem animi odit sapiente neque nulla officia doloribus praesentium. Quasi.</p>
    </main>

    <?php require_once __DIR__ . '\..\components\footer.php'; ?>
</body>
</html>

 